name: Composite workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Use my composite action
          uses: ./.github/actions
          with:
            node-version: '18'