name: env job
on: 
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'log level'
        required: true
        default: 'warning'
  
jobs:
  job1:
    runs-on: linuxg19
    steps:
      - name: step1
        env:
          stepVar1: stepvalue1
        run: |
          echo "The value for stepvar1: $stepVar1"

