name: Output testing
on: 
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.stesp1.outputs.test }}
            output2: ${{ steps.stesp1.outputs.test }}
        steps:
            - id: step1
              run: echo "test=hello" >> "$GITHUB_OUTPUT"
            - id: step2
              run: echo "test=World" >> "$GITHUB_OUTPUT"
            - id: step3
              run: echo "$OUTPUT1 $OUTPUT2"
            - name: show the ref
              run: echo "${{ github.ref }}"

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - env:
                OUTPUT1: ${{needs.job1.outputs.output1}}
                OUTPUT2: ${{needs.job1.outputs.output2}}
              run: echo "$OUTPUT1 $OUTPUT2"